
export const CATEGORIES = [
  "bend/bow",
  "crawl", 
  "crouch/kneel",
  "dance",
  "fall down",
  "get up",
  "jump/leap",
  "lie/sleep",
  "martial art",
  "run/jog",
  "sit",
  "stand",
  "swim",
  "walk",
  "answer phone",
  "brush teeth",
  "carry/hold sth.",
  "catch sth.",
  "chop",
  "climb",
  "clink glass",
  "close",
  "cook",
  "cut",
  "dig",
  "dress/put on clothing",
  "drink",
  "drive",
  "eat",
  "enter",
  "exit",
  "extract",
  "fishing",
  "hit sth.",
  "kick sth.",
  "lift/pick up",
  "listen to sth.",
  "open",
  "paint",
  "play board game",
  "play musical instrument",
  "play with pets",
  "point to sth.",
  "press",
  "pull sth.",
  "push sth.",
  "put down",
  "read",
  "ride",
  "row boat",
  "sail boat",
  "shoot",
  "shovel",
  "smoke",
  "stir",
  "take a photo",
  "look at a cellphone",
  "throw",
  "touch sth.",
  "turn",
  "watch screen",
  "work on a computer",
  "write",
  "fight/hit sb.",
  "give/serve sth. to sb.",
  "grab sb.",
  "hand clap",
  "hand shake",
  "hand wave",
  "hug sb.",
  "kick sb.",
  "kiss sb.",
  "lift sb.",
  "listen to sb.",
  "play with kids",
  "push sb.",
  "sing",
  "take sth. from sb.",
  "talk",
  "watch sb.",
];
